# 순서
0. one-hot-encoding (O or X)
1. NULL값 분류(그대로 or 컬럼 삭제)
2. 데이터 나누기 (train_test_split)
3. SMOTE(오버샘플링)
4. 스케일링(없음, MinMaxScaler, StandardScaler, RobusterScaler)


In [1]:
# scaler 
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import RobustScaler
from sklearn.preprocessing import StandardScaler


# resampling
from imblearn.over_sampling import SMOTE



## 데이터 불러오기

In [175]:
socar_df = pd.read_csv("insurance_fraud_detect_data.csv")
socar = socar_df.copy()
socar.tail()

fraud_YN  car_model  sharing_type  age_group  has_previous_accident  \
15995         0          2             0          2                      0   
15996         0          2             0          2                      1   
15997         0          2             1          2                      0   
15998         0          2             0          2                      0   
15999         0          2             0          2                      0   

       cumulative_use_count  b2b  accident_ratio  pf_type  socarpass  ...  \
15995                     2    0             100        2          0  ...   
15996                     4    0             100        1          1  ...   
15997                     4    0             100        1          0  ...   
15998                     2    0             100        2          0  ...   
15999                     1    0             100        1          0  ...   

       insure_cost  accident_location  car_part1  car_part2  repair_cnt  \
15995            0                  1          1          0           1   
15996            0                  2          1          0           1   
15997            0                  0          0          0           1   
15998            0                  4          1          0           1   
15999      1188750                  2          0          0           1   

       acc_type1  insurance_site_aid_YN  police_site_aid_YN  total_prsn_cnt  \
15995          0                      0                   0              -1   
15996          0                      0                   0              -1   
15997          0                      0                   0              -1   
15998          0                      0                   0              -1   
15999          0                      0                   0              -1   

       test_set  
15995         0  
15996         0  
15997         1  
15998         0  
15999         0  

[5 rows x 25 columns]

- null값이 들어있는 컬럼
    - accident_hour : -1 - 36개
    - repair_cost : 0 - 6006개
    - insure_cost : 0 - 10424개
    - accident_location : 5(확인불가) - 288개
    - acc_type1 : 0 - 11384개
    - insurnace_site_aid_YN : 0 - 11325개
    - police_site_aid_YN :  0 - 11328개
    - total_prsn_cnt :  -1 - 11358개

# [원핫인코딩 쓰지 않는 8가지 경우 !]

--------------------------------------------------------------------------------------------

## < 1. 첫번째 방법 (NULL 유지 , SMOTE, 스케일링 없음) >

## (1) NULL 유지, (2) 데이터 분리

In [176]:
from sklearn.model_selection import train_test_split

# train_set, test_set 분리
train_set = socar[socar["test_set"] == 0]
test_set = socar[socar["test_set"] == 1]

# "test_set" 컬럼 삭제
train_set = train_set.drop("test_set", axis=1)  # test_set = 0인 애들이고, test_set 컬럼을 삭제
test_set = test_set.drop("test_set", axis=1)    # test_set = 1인 애들이고, test_set 컬럼을 삭제

# features와 target분리
X = train_set.drop("fraud_YN", axis=1)         # train_set에서 y라벨 데이터 지움
y = train_set["fraud_YN"]                      # 라벨데이터만 가지고 y변수에 할당

X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.2, random_state=13, stratify=y)
X_test, y_test = test_set.drop("fraud_YN", axis=1), test_set["fraud_YN"]

## (3) SMOTE

In [189]:
#  X : test column = 0 , y : test column = 1

from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=13)
X_train_over, y_train_over = smote.fit_resample(X, y)  

In [190]:
X.shape, y.shape

((12879, 23), (12879,))

In [191]:
X_train_over.shape, y_train_over.shape

((25690, 23), (25690,))

In [193]:
print(np.unique(y, return_counts=True))
print(np.unique(y_train_over, return_counts=True))

(array([0, 1], dtype=int64), array([12845,    34], dtype=int64))
(array([0, 1], dtype=int64), array([12845, 12845], dtype=int64))


## < 2. 두번째 방법 (NULL 유지 , SMOTE, 스케일링 Minmax) >

## (1) NULL 유지, (2) 데이터 분리

In [194]:
from sklearn.model_selection import train_test_split

# train_set, test_set 분리
train_set = socar[socar["test_set"] == 0]
test_set = socar[socar["test_set"] == 1]

# "test_set" 컬럼 삭제
train_set = train_set.drop("test_set", axis=1)  # test_set = 0인 애들이고, test_set 컬럼을 삭제
test_set = test_set.drop("test_set", axis=1)    # test_set = 1인 애들이고, test_set 컬럼을 삭제

# features와 target분리
X = train_set.drop("fraud_YN", axis=1)         # train_set에서 y라벨 데이터 지움
y = train_set["fraud_YN"]                      # 라벨데이터만 가지고 y변수에 할당

X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.2, random_state=13, stratify=y)
X_test, y_test = test_set.drop("fraud_YN", axis=1), test_set["fraud_YN"]

## (3) SMOTE

In [195]:
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=13)
X_train_over, y_train_over = smote.fit_resample(X, y)

In [197]:
X.shape, y.shape

((12879, 23), (12879,))

In [198]:
X_train_over.shape, y_train_over.shape

((25690, 23), (25690,))

In [200]:
print(np.unique(y, return_counts=True))
print(np.unique(y_train_over, return_counts=True))

(array([0, 1], dtype=int64), array([12845,    34], dtype=int64))
(array([0, 1], dtype=int64), array([12845, 12845], dtype=int64))


## (4) 스케일링

In [201]:
from sklearn.preprocessing import MinMaxScaler

MMS = MinMaxScaler()

MMS.fit(X)

X_mms = MMS.transform(X)

In [202]:
X_mms_pd2 = pd.DataFrame(X_mms, columns=X.columns)
X_mms_pd2    

car_model  sharing_type  age_group  has_previous_accident  \
0           0.25           1.0       0.50                    0.0   
1           0.50           1.0       0.50                    0.0   
2           0.00           0.0       0.00                    0.0   
3           0.00           1.0       0.50                    0.0   
4           0.25           0.0       0.75                    0.0   
...          ...           ...        ...                    ...   
12874       0.25           0.0       0.50                    1.0   
12875       0.25           0.0       0.25                    0.0   
12876       0.25           0.0       0.25                    1.0   
12877       0.25           0.0       0.25                    0.0   
12878       0.25           0.0       0.25                    0.0   

       cumulative_use_count  b2b  accident_ratio  pf_type  socarpass  \
0                  0.333333  0.0             1.0      0.5        0.0   
1                  1.000000  0.0             0.0      0.5        0.0   
2                  0.000000  0.0             1.0      0.0        0.0   
3                  1.000000  0.0             1.0      1.0        0.0   
4                  1.000000  0.0             0.0      0.0        0.0   
...                     ...  ...             ...      ...        ...   
12874              1.000000  0.0             1.0      0.0        0.0   
12875              0.333333  0.0             1.0      0.5        0.0   
12876              1.000000  0.0             1.0      0.0        1.0   
12877              0.333333  0.0             1.0      0.5        0.0   
12878              0.000000  0.0             1.0      0.0        0.0   

       socarsave  ...  repair_cost  insure_cost  accident_location  car_part1  \
0            0.0  ...     0.013409     0.000000                0.2        0.0   
1            0.0  ...     0.138052     0.000000                0.6        1.0   
2            0.0  ...     0.053947     0.012769                0.2        0.0   
3            0.0  ...     0.000000     0.012852                0.0        0.0   
4            0.0  ...     0.000000     0.000000                0.2        0.0   
...          ...  ...          ...          ...                ...        ...   
12874        0.0  ...     0.068696     0.000000                0.0        0.0   
12875        0.0  ...     0.000000     0.000000                0.2        1.0   
12876        0.0  ...     0.063666     0.000000                0.4        1.0   
12877        0.0  ...     0.000000     0.000000                0.8        1.0   
12878        0.0  ...     0.040310     0.012551                0.4        0.0   

       car_part2  repair_cnt  acc_type1  insurance_site_aid_YN  \
0            0.0    0.027027   0.000000                    0.0   
1            0.0    0.027027   0.000000                    0.0   
2            0.0    0.054054   0.000000                    0.0   
3            0.0    0.027027   0.333333                    1.0   
4            0.0    0.027027   0.333333                    0.5   
...          ...         ...        ...                    ...   
12874        0.0    0.027027   0.000000                    0.0   
12875        0.0    0.027027   0.000000                    0.0   
12876        0.0    0.027027   0.000000                    0.0   
12877        0.0    0.027027   0.000000                    0.0   
12878        0.0    0.027027   0.000000                    0.0   

       police_site_aid_YN  total_prsn_cnt  
0                     0.0             0.0  
1                     0.0             0.0  
2                     0.0             0.0  
3                     1.0             0.5  
4                     1.0             0.5  
...                   ...             ...  
12874                 0.0             0.0  
12875                 0.0             0.0  
12876                 0.0             0.0  
12877                 0.0             0.0  
12878                 0.0             0.0  

[12879 rows x 23 columns]

   ## <3. 세번째 방법 (NULL 유지, SMOTE, 스케일링(Standard))

## (1) NULL 유지, (2) 데이터 분리

In [203]:
from sklearn.model_selection import train_test_split

# train_set, test_set 분리
train_set = socar[socar["test_set"] == 0]
test_set = socar[socar["test_set"] == 1]

# "test_set" 컬럼 삭제
train_set = train_set.drop("test_set", axis=1)  # test_set = 0인 애들이고, test_set 컬럼을 삭제
test_set = test_set.drop("test_set", axis=1)    # test_set = 1인 애들이고, test_set 컬럼을 삭제

# features와 target분리
X = train_set.drop("fraud_YN", axis=1)         # train_set에서 y라벨 데이터 지움
y = train_set["fraud_YN"]                      # 라벨데이터만 가지고 y변수에 할당

X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.2, random_state=13, stratify=y)
X_test, y_test = test_set.drop("fraud_YN", axis=1), test_set["fraud_YN"]

## (3) SMOTE

In [204]:
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=13)
X_train_over, y_train_over = smote.fit_resample(X, y)

In [205]:
X.shape, y.shape

((12879, 23), (12879,))

In [206]:
X_train_over.shape, y_train_over.shape

((25690, 23), (25690,))

In [207]:
print(np.unique(y, return_counts=True))
print(np.unique(y_train_over, return_counts=True))

(array([0, 1], dtype=int64), array([12845,    34], dtype=int64))
(array([0, 1], dtype=int64), array([12845, 12845], dtype=int64))


## (4) 스케일링

In [208]:
from sklearn.preprocessing import StandardScaler

SS = StandardScaler()

SS.fit(X)

X_ss = SS.transform(X)

In [209]:
X_ss_pd3 = pd.DataFrame(X_ss, columns=X.columns)
X_ss_pd3

car_model  sharing_type  age_group  has_previous_accident  \
0       0.394060      2.375307   0.446391              -0.286191   
1       1.701738      2.375307   0.446391              -0.286191   
2      -0.913618     -0.420998  -1.260072              -0.286191   
3      -0.913618      2.375307   0.446391              -0.286191   
4       0.394060     -0.420998   1.299623              -0.286191   
...          ...           ...        ...                    ...   
12874   0.394060     -0.420998   0.446391               3.494171   
12875   0.394060     -0.420998  -0.406840              -0.286191   
12876   0.394060     -0.420998  -0.406840               3.494171   
12877   0.394060     -0.420998  -0.406840              -0.286191   
12878   0.394060     -0.420998  -0.406840              -0.286191   

       cumulative_use_count      b2b  accident_ratio   pf_type  socarpass  \
0                 -0.456499 -0.07906        0.367925  0.330723  -0.389434   
1                  1.262329 -0.07906       -3.009481  0.330723  -0.389434   
2                 -1.315913 -0.07906        0.367925 -1.049503  -0.389434   
3                  1.262329 -0.07906        0.367925  1.710948  -0.389434   
4                  1.262329 -0.07906       -3.009481 -1.049503  -0.389434   
...                     ...      ...             ...       ...        ...   
12874              1.262329 -0.07906        0.367925 -1.049503  -0.389434   
12875             -0.456499 -0.07906        0.367925  0.330723  -0.389434   
12876              1.262329 -0.07906        0.367925 -1.049503   2.567830   
12877             -0.456499 -0.07906        0.367925  0.330723  -0.389434   
12878             -1.315913 -0.07906        0.367925 -1.049503  -0.389434   

       socarsave  ...  repair_cost  insure_cost  accident_location  car_part1  \
0      -0.277199  ...    -0.296588    -0.273447          -0.222456  -0.697001   
1      -0.277199  ...     2.047627    -0.273447           1.276766   1.434719   
2      -0.277199  ...     0.465826     0.121310          -0.222456  -0.697001   
3      -0.277199  ...    -0.548781     0.123879          -0.972067  -0.697001   
4      -0.277199  ...    -0.548781    -0.273447          -0.222456  -0.697001   
...          ...  ...          ...          ...                ...        ...   
12874  -0.277199  ...     0.743205    -0.273447          -0.972067  -0.697001   
12875  -0.277199  ...    -0.548781    -0.273447          -0.222456   1.434719   
12876  -0.277199  ...     0.648616    -0.273447           0.527155   1.434719   
12877  -0.277199  ...    -0.548781    -0.273447           2.026377   1.434719   
12878  -0.277199  ...     0.209342     0.114566           0.527155  -0.697001   

       car_part2  repair_cnt  acc_type1  insurance_site_aid_YN  \
0      -0.454134   -0.382028  -0.548692              -0.533500   
1      -0.454134   -0.382028  -0.548692              -0.533500   
2      -0.454134    0.672890  -0.548692              -0.533500   
3      -0.454134   -0.382028   1.609049               2.914039   
4      -0.454134   -0.382028   1.609049               1.190269   
...          ...         ...        ...                    ...   
12874  -0.454134   -0.382028  -0.548692              -0.533500   
12875  -0.454134   -0.382028  -0.548692              -0.533500   
12876  -0.454134   -0.382028  -0.548692              -0.533500   
12877  -0.454134   -0.382028  -0.548692              -0.533500   
12878  -0.454134   -0.382028  -0.548692              -0.533500   

       police_site_aid_YN  total_prsn_cnt  
0               -0.574272       -0.484501  
1               -0.574272       -0.484501  
2               -0.574272       -0.484501  
3                1.741335        2.649547  
4                1.741335        2.649547  
...                   ...             ...  
12874           -0.574272       -0.484501  
12875           -0.574272       -0.484501  
12876           -0.574272       -0.484501  
12877           -0.574272       -0.484501  
12878          

   ## <4. 네번째 방법 (NULL 유지, SMOTE, 스케일링(Robust))

## (1) NULL 유지, (2) 데이터 분리

In [210]:
from sklearn.model_selection import train_test_split

# train_set, test_set 분리
train_set = socar[socar["test_set"] == 0]
test_set = socar[socar["test_set"] == 1]

# "test_set" 컬럼 삭제
train_set = train_set.drop("test_set", axis=1)  # test_set = 0인 애들이고, test_set 컬럼을 삭제
test_set = test_set.drop("test_set", axis=1)    # test_set = 1인 애들이고, test_set 컬럼을 삭제

# features와 target분리
X = train_set.drop("fraud_YN", axis=1)         # train_set에서 y라벨 데이터 지움
y = train_set["fraud_YN"]                      # 라벨데이터만 가지고 y변수에 할당

X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.2, random_state=13, stratify=y)
X_test, y_test = test_set.drop("fraud_YN", axis=1), test_set["fraud_YN"]

## (3) SMOTE

In [213]:
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=13)
X_train_over, y_train_over = smote.fit_resample(X, y)

In [214]:
print(np.unique(y, return_counts=True))
print(np.unique(y_train_over, return_counts=True))

(array([0, 1], dtype=int64), array([12845,    34], dtype=int64))
(array([0, 1], dtype=int64), array([12845, 12845], dtype=int64))


## (4) 스케일링

In [215]:
from sklearn.preprocessing import RobustScaler

RS = RobustScaler()

RS.fit(X)

X_rs = RS.transform(X)

In [216]:
X_rs_pd4 = pd.DataFrame(X_rs, columns=X.columns)
X_rs_pd4

car_model  sharing_type  age_group  has_previous_accident  \
0            0.0           1.0        1.0                    0.0   
1            1.0           1.0        1.0                    0.0   
2           -1.0           0.0       -1.0                    0.0   
3           -1.0           1.0        1.0                    0.0   
4            0.0           0.0        2.0                    0.0   
...          ...           ...        ...                    ...   
12874        0.0           0.0        1.0                    1.0   
12875        0.0           0.0        0.0                    0.0   
12876        0.0           0.0        0.0                    1.0   
12877        0.0           0.0        0.0                    0.0   
12878        0.0           0.0        0.0                    0.0   

       cumulative_use_count  b2b  accident_ratio  pf_type  socarpass  \
0                       0.0  0.0             0.0      0.0        0.0   
1                       1.0  0.0          -100.0      0.0        0.0   
2                      -0.5  0.0             0.0     -1.0        0.0   
3                       1.0  0.0             0.0      1.0        0.0   
4                       1.0  0.0          -100.0     -1.0        0.0   
...                     ...  ...             ...      ...        ...   
12874                   1.0  0.0             0.0     -1.0        0.0   
12875                   0.0  0.0             0.0      0.0        0.0   
12876                   1.0  0.0             0.0     -1.0        1.0   
12877                   0.0  0.0             0.0      0.0        0.0   
12878                  -0.5  0.0             0.0     -1.0        0.0   

       socarsave  ...  repair_cost  insure_cost  accident_location  car_part1  \
0            0.0  ...    -0.161562     0.000000                0.0        0.0   
1            0.0  ...     3.181826     0.000000                1.0        1.0   
2            0.0  ...     0.925814     2.180512                0.0        0.0   
3            0.0  ...    -0.521249     2.194701               -0.5        0.0   
4            0.0  ...    -0.521249     0.000000                0.0        0.0   
...          ...  ...          ...          ...                ...        ...   
12874        0.0  ...     1.321421     0.000000               -0.5        0.0   
12875        0.0  ...    -0.521249     0.000000                0.0        1.0   
12876        0.0  ...     1.186516     0.000000                0.5        1.0   
12877        0.0  ...    -0.521249     0.000000                1.5        1.0   
12878        0.0  ...     0.560009     2.143263                0.5        0.0   

       car_part2  repair_cnt  acc_type1  insurance_site_aid_YN  \
0            0.0         0.0        0.0                    0.0   
1            0.0         0.0        0.0                    0.0   
2            0.0         1.0        0.0                    0.0   
3            0.0         0.0        1.0                    2.0   
4            0.0         0.0        1.0                    1.0   
...          ...         ...        ...                    ...   
12874        0.0         0.0        0.0                    0.0   
12875        0.0         0.0        0.0                    0.0   
12876        0.0         0.0        0.0                    0.0   
12877        0.0         0.0        0.0                    0.0   
12878        0.0         0.0        0.0                    0.0   

       police_site_aid_YN  total_prsn_cnt  
0                     0.0             0.0  
1                     0.0             0.0  
2                     0.0             0.0  
3                     1.0             3.0  
4                     1.0             3.0  
...                   ...             ...  
12874                 0.0             0.0  
12875                 0.0             0.0  
12876                 0.0             0.0  
12877                 0.0             0.0  
12878                 0.0             0.0  

[12879 rows x 23 columns]

   ## <5. 다섯번째 방법 (NULL 데이터 컬럼 삭제, SMOTE, 스케일링 없음))

## (1) NULL값 삭제 

- null값이 들어있는 컬럼
    - accident_hour : -1 - 36개
    - repair_cost : 0 - 6006개
    - insure_cost : 0 - 10424개
    - accident_location : 5(확인불가) - 288개
    - acc_type1 : 0 - 11384개
    - insurnace_site_aid_YN : 0 - 11325개
    - police_site_aid_YN :  0 - 11328개
    - total_prsn_cnt :  -1 - 11358개

In [217]:
socar_delete = socar.drop(['accident_hour', 'repair_cost', 'insure_cost', 'accident_location', 'acc_type1', 'insurance_site_aid_YN', 'police_site_aid_YN', 'total_prsn_cnt'], axis=1)
socar_delete

fraud_YN  car_model  sharing_type  age_group  has_previous_accident  \
0             0          2             1          3                      0   
1             0          1             0          4                      0   
2             0          1             0          4                      1   
3             0          3             1          3                      0   
4             0          1             0          1                      0   
...         ...        ...           ...        ...                    ...   
15995         0          2             0          2                      0   
15996         0          2             0          2                      1   
15997         0          2             1          2                      0   
15998         0          2             0          2                      0   
15999         0          2             0          2                      0   

       cumulative_use_count  b2b  accident_ratio  pf_type  socarpass  \
0                         2    0             100        2          0   
1                         4    0               0        3          1   
2                         4    0             100        3          1   
3                         4    0               0        2          0   
4                         1    0             100        1          0   
...                     ...  ...             ...      ...        ...   
15995                     2    0             100        2          0   
15996                     4    0             100        1          1   
15997                     4    0             100        1          0   
15998                     2    0             100        2          0   
15999                     1    0             100        1          0   

       socarsave  start_hour  duration  car_part1  car_part2  repair_cnt  \
0              0           4         2          0          0           1   
1              0           1         4          1          1           2   
2              0           1         4          1          0           2   
3              0           3         3          1          0           1   
4              0           1         1          0          0           2   
...          ...         ...       ...        ...        ...         ...   
15995          0           1         1          1          0           1   
15996          0           5         2          1          0           1   
15997          0           1         3          0          0           1   
15998          0           6         1          1          0           1   
15999          0           6         5          0          0           1   

       test_set  
0             0  
1             1  
2             1  
3             0  
4             0  
...         ...  
15995         0  
15996         0  
15997         1  
15998         0  
15999         0  

[16000 rows x 17 columns]

## (2) 데이터 분리

In [218]:
from sklearn.model_selection import train_test_split

# train_set, test_set 분리
train_set = socar_delete[socar_delete["test_set"] == 0]
test_set = socar_delete[socar_delete["test_set"] == 1]

# "test_set" 컬럼 삭제
train_set = train_set.drop("test_set", axis=1)  # test_set = 0인 애들이고, test_set 컬럼을 삭제
test_set = test_set.drop("test_set", axis=1)    # test_set = 1인 애들이고, test_set 컬럼을 삭제

# features와 target분리
X = train_set.drop("fraud_YN", axis=1)         # train_set에서 y라벨 데이터 지움
y = train_set["fraud_YN"]                      # 라벨데이터만 가지고 y변수에 할당

X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.2, random_state=13, stratify=y)
X_test, y_test = test_set.drop("fraud_YN", axis=1), test_set["fraud_YN"]

## (3) SMOTE

In [219]:
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=13)
X_train_over, y_train_over = smote.fit_resample(X, y)

In [221]:
print(np.unique(y, return_counts=True))
print(np.unique(y_train_over, return_counts=True))

(array([0, 1], dtype=int64), array([12845,    34], dtype=int64))
(array([0, 1], dtype=int64), array([12845, 12845], dtype=int64))


## (4) 스케일링 없음

   ## <6. 여섯번째 방법 (NULL 데이터 컬럼 삭제, SMOTE, 스케일링 MinMax))

## (1) NULL값 삭제 

In [227]:
socar_delete = socar.drop(['accident_hour', 'repair_cost', 'insure_cost', 'accident_location', 'acc_type1', 'insurance_site_aid_YN', 'police_site_aid_YN', 'total_prsn_cnt'], axis=1)
socar_delete

fraud_YN  car_model  sharing_type  age_group  has_previous_accident  \
0             0          2             1          3                      0   
1             0          1             0          4                      0   
2             0          1             0          4                      1   
3             0          3             1          3                      0   
4             0          1             0          1                      0   
...         ...        ...           ...        ...                    ...   
15995         0          2             0          2                      0   
15996         0          2             0          2                      1   
15997         0          2             1          2                      0   
15998         0          2             0          2                      0   
15999         0          2             0          2                      0   

       cumulative_use_count  b2b  accident_ratio  pf_type  socarpass  \
0                         2    0             100        2          0   
1                         4    0               0        3          1   
2                         4    0             100        3          1   
3                         4    0               0        2          0   
4                         1    0             100        1          0   
...                     ...  ...             ...      ...        ...   
15995                     2    0             100        2          0   
15996                     4    0             100        1          1   
15997                     4    0             100        1          0   
15998                     2    0             100        2          0   
15999                     1    0             100        1          0   

       socarsave  start_hour  duration  car_part1  car_part2  repair_cnt  \
0              0           4         2          0          0           1   
1              0           1         4          1          1           2   
2              0           1         4          1          0           2   
3              0           3         3          1          0           1   
4              0           1         1          0          0           2   
...          ...         ...       ...        ...        ...         ...   
15995          0           1         1          1          0           1   
15996          0           5         2          1          0           1   
15997          0           1         3          0          0           1   
15998          0           6         1          1          0           1   
15999          0           6         5          0          0           1   

       test_set  
0             0  
1             1  
2             1  
3             0  
4             0  
...         ...  
15995         0  
15996         0  
15997         1  
15998         0  
15999         0  

[16000 rows x 17 columns]

## (2) 데이터 분리

In [228]:
from sklearn.model_selection import train_test_split

# train_set, test_set 분리
train_set = socar_delete[socar_delete["test_set"] == 0]
test_set = socar_delete[socar_delete["test_set"] == 1]

# "test_set" 컬럼 삭제
train_set = train_set.drop("test_set", axis=1)  # test_set = 0인 애들이고, test_set 컬럼을 삭제
test_set = test_set.drop("test_set", axis=1)    # test_set = 1인 애들이고, test_set 컬럼을 삭제

# features와 target분리
X = train_set.drop("fraud_YN", axis=1)         # train_set에서 y라벨 데이터 지움
y = train_set["fraud_YN"]                      # 라벨데이터만 가지고 y변수에 할당

X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.2, random_state=13, stratify=y)
X_test, y_test = test_set.drop("fraud_YN", axis=1), test_set["fraud_YN"]

## (3) SMOTE

In [229]:
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=13)
X_train_over, y_train_over = smote.fit_resample(X, y)

In [230]:
print(np.unique(y, return_counts=True))
print(np.unique(y_train_over, return_counts=True))

(array([0, 1], dtype=int64), array([12845,    34], dtype=int64))
(array([0, 1], dtype=int64), array([12845, 12845], dtype=int64))


## (4) 스케일링

In [231]:
from sklearn.preprocessing import MinMaxScaler

MMS = MinMaxScaler()

MMS.fit(X)

X_mms = MMS.transform(X)

In [235]:
X_mms_pd6 = pd.DataFrame(X_mms, columns=X.columns)
X_mms_pd6

car_model  sharing_type  age_group  has_previous_accident  \
0           0.25           1.0       0.50                    0.0   
1           0.50           1.0       0.50                    0.0   
2           0.00           0.0       0.00                    0.0   
3           0.00           1.0       0.50                    0.0   
4           0.25           0.0       0.75                    0.0   
...          ...           ...        ...                    ...   
12874       0.25           0.0       0.50                    1.0   
12875       0.25           0.0       0.25                    0.0   
12876       0.25           0.0       0.25                    1.0   
12877       0.25           0.0       0.25                    0.0   
12878       0.25           0.0       0.25                    0.0   

       cumulative_use_count  b2b  accident_ratio  pf_type  socarpass  \
0                  0.333333  0.0             1.0      0.5        0.0   
1                  1.000000  0.0             0.0      0.5        0.0   
2                  0.000000  0.0             1.0      0.0        0.0   
3                  1.000000  0.0             1.0      1.0        0.0   
4                  1.000000  0.0             0.0      0.0        0.0   
...                     ...  ...             ...      ...        ...   
12874              1.000000  0.0             1.0      0.0        0.0   
12875              0.333333  0.0             1.0      0.5        0.0   
12876              1.000000  0.0             1.0      0.0        1.0   
12877              0.333333  0.0             1.0      0.5        0.0   
12878              0.000000  0.0             1.0      0.0        0.0   

       socarsave  start_hour  duration  car_part1  car_part2  repair_cnt  
0            0.0         0.6      0.25        0.0        0.0    0.027027  
1            0.0         0.4      0.50        1.0        0.0    0.027027  
2            0.0         0.0      0.00        0.0        0.0    0.054054  
3            0.0         1.0      0.50        0.0        0.0    0.027027  
4            0.0         0.6      0.25        0.0        0.0    0.027027  
...          ...         ...       ...        ...        ...         ...  
12874        0.0         0.6      0.00        0.0        0.0    0.027027  
12875        0.0         0.0      0.00        1.0        0.0    0.027027  
12876        0.0         0.8      0.25        1.0        0.0    0.027027  
12877        0.0         1.0      0.00        1.0        0.0    0.027027  
12878        0.0         1.0      1.00        0.0        0.0    0.027027  

[12879 rows x 15 columns]

   ## <7. 일곱번째 방법 (NULL 데이터 컬럼 삭제, SMOTE, 스케일링 Standard))

## (1) NULL값 삭제 

In [236]:
socar_delete = socar.drop(['accident_hour', 'repair_cost', 'insure_cost', 'accident_location', 'acc_type1', 'insurance_site_aid_YN', 'police_site_aid_YN', 'total_prsn_cnt'], axis=1)
socar_delete

fraud_YN  car_model  sharing_type  age_group  has_previous_accident  \
0             0          2             1          3                      0   
1             0          1             0          4                      0   
2             0          1             0          4                      1   
3             0          3             1          3                      0   
4             0          1             0          1                      0   
...         ...        ...           ...        ...                    ...   
15995         0          2             0          2                      0   
15996         0          2             0          2                      1   
15997         0          2             1          2                      0   
15998         0          2             0          2                      0   
15999         0          2             0          2                      0   

       cumulative_use_count  b2b  accident_ratio  pf_type  socarpass  \
0                         2    0             100        2          0   
1                         4    0               0        3          1   
2                         4    0             100        3          1   
3                         4    0               0        2          0   
4                         1    0             100        1          0   
...                     ...  ...             ...      ...        ...   
15995                     2    0             100        2          0   
15996                     4    0             100        1          1   
15997                     4    0             100        1          0   
15998                     2    0             100        2          0   
15999                     1    0             100        1          0   

       socarsave  start_hour  duration  car_part1  car_part2  repair_cnt  \
0              0           4         2          0          0           1   
1              0           1         4          1          1           2   
2              0           1         4          1          0           2   
3              0           3         3          1          0           1   
4              0           1         1          0          0           2   
...          ...         ...       ...        ...        ...         ...   
15995          0           1         1          1          0           1   
15996          0           5         2          1          0           1   
15997          0           1         3          0          0           1   
15998          0           6         1          1          0           1   
15999          0           6         5          0          0           1   

       test_set  
0             0  
1             1  
2             1  
3             0  
4             0  
...         ...  
15995         0  
15996         0  
15997         1  
15998         0  
15999         0  

[16000 rows x 17 columns]

## (2) 데이터 분리

In [237]:
from sklearn.model_selection import train_test_split

# train_set, test_set 분리
train_set = socar_delete[socar_delete["test_set"] == 0]
test_set = socar_delete[socar_delete["test_set"] == 1]

# "test_set" 컬럼 삭제
train_set = train_set.drop("test_set", axis=1)  # test_set = 0인 애들이고, test_set 컬럼을 삭제
test_set = test_set.drop("test_set", axis=1)    # test_set = 1인 애들이고, test_set 컬럼을 삭제

# features와 target분리
X = train_set.drop("fraud_YN", axis=1)         # train_set에서 y라벨 데이터 지움
y = train_set["fraud_YN"]                      # 라벨데이터만 가지고 y변수에 할당

X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.2, random_state=13, stratify=y)
X_test, y_test = test_set.drop("fraud_YN", axis=1), test_set["fraud_YN"]

## (3) SMOTE

In [238]:
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=13)
X_train_over, y_train_over = smote.fit_resample(X, y)

In [239]:
print(np.unique(y, return_counts=True))
print(np.unique(y_train_over, return_counts=True))

(array([0, 1], dtype=int64), array([12845,    34], dtype=int64))
(array([0, 1], dtype=int64), array([12845, 12845], dtype=int64))


## (4) 스케일링

In [240]:
from sklearn.preprocessing import StandardScaler

SS = StandardScaler()

SS.fit(X)

X_ss = SS.transform(X)

In [241]:
X_ss_pd7 = pd.DataFrame(X_ss, columns=X.columns)
X_ss_pd7

car_model  sharing_type  age_group  has_previous_accident  \
0       0.394060      2.375307   0.446391              -0.286191   
1       1.701738      2.375307   0.446391              -0.286191   
2      -0.913618     -0.420998  -1.260072              -0.286191   
3      -0.913618      2.375307   0.446391              -0.286191   
4       0.394060     -0.420998   1.299623              -0.286191   
...          ...           ...        ...                    ...   
12874   0.394060     -0.420998   0.446391               3.494171   
12875   0.394060     -0.420998  -0.406840              -0.286191   
12876   0.394060     -0.420998  -0.406840               3.494171   
12877   0.394060     -0.420998  -0.406840              -0.286191   
12878   0.394060     -0.420998  -0.406840              -0.286191   

       cumulative_use_count      b2b  accident_ratio   pf_type  socarpass  \
0                 -0.456499 -0.07906        0.367925  0.330723  -0.389434   
1                  1.262329 -0.07906       -3.009481  0.330723  -0.389434   
2                 -1.315913 -0.07906        0.367925 -1.049503  -0.389434   
3                  1.262329 -0.07906        0.367925  1.710948  -0.389434   
4                  1.262329 -0.07906       -3.009481 -1.049503  -0.389434   
...                     ...      ...             ...       ...        ...   
12874              1.262329 -0.07906        0.367925 -1.049503  -0.389434   
12875             -0.456499 -0.07906        0.367925  0.330723  -0.389434   
12876              1.262329 -0.07906        0.367925 -1.049503   2.567830   
12877             -0.456499 -0.07906        0.367925  0.330723  -0.389434   
12878             -1.315913 -0.07906        0.367925 -1.049503  -0.389434   

       socarsave  start_hour  duration  car_part1  car_part2  repair_cnt  
0      -0.277199    0.156612 -0.216316  -0.697001  -0.454134   -0.382028  
1      -0.277199   -0.424491  0.646202   1.434719  -0.454134   -0.382028  
2      -0.277199   -1.586698 -1.078834  -0.697001  -0.454134    0.672890  
3      -0.277199    1.318819  0.646202  -0.697001  -0.454134   -0.382028  
4      -0.277199    0.156612 -0.216316  -0.697001  -0.454134   -0.382028  
...          ...         ...       ...        ...        ...         ...  
12874  -0.277199    0.156612 -1.078834  -0.697001  -0.454134   -0.382028  
12875  -0.277199   -1.586698 -1.078834   1.434719  -0.454134   -0.382028  
12876  -0.277199    0.737716 -0.216316   1.434719  -0.454134   -0.382028  
12877  -0.277199    1.318819 -1.078834   1.434719  -0.454134   -0.382028  
12878  -0.277199    1.318819  2.371239  -0.697001  -0.454134   -0.382028  

[12879 rows x 15 columns]

   ## <8. 여덟번째 방법 (NULL 데이터 컬럼 삭제, SMOTE, 스케일링 Robust))

## (1) NULL값 삭제 

In [242]:
socar_delete = socar.drop(['accident_hour', 'repair_cost', 'insure_cost', 'accident_location', 'acc_type1', 'insurance_site_aid_YN', 'police_site_aid_YN', 'total_prsn_cnt'], axis=1)
socar_delete

fraud_YN  car_model  sharing_type  age_group  has_previous_accident  \
0             0          2             1          3                      0   
1             0          1             0          4                      0   
2             0          1             0          4                      1   
3             0          3             1          3                      0   
4             0          1             0          1                      0   
...         ...        ...           ...        ...                    ...   
15995         0          2             0          2                      0   
15996         0          2             0          2                      1   
15997         0          2             1          2                      0   
15998         0          2             0          2                      0   
15999         0          2             0          2                      0   

       cumulative_use_count  b2b  accident_ratio  pf_type  socarpass  \
0                         2    0             100        2          0   
1                         4    0               0        3          1   
2                         4    0             100        3          1   
3                         4    0               0        2          0   
4                         1    0             100        1          0   
...                     ...  ...             ...      ...        ...   
15995                     2    0             100        2          0   
15996                     4    0             100        1          1   
15997                     4    0             100        1          0   
15998                     2    0             100        2          0   
15999                     1    0             100        1          0   

       socarsave  start_hour  duration  car_part1  car_part2  repair_cnt  \
0              0           4         2          0          0           1   
1              0           1         4          1          1           2   
2              0           1         4          1          0           2   
3              0           3         3          1          0           1   
4              0           1         1          0          0           2   
...          ...         ...       ...        ...        ...         ...   
15995          0           1         1          1          0           1   
15996          0           5         2          1          0           1   
15997          0           1         3          0          0           1   
15998          0           6         1          1          0           1   
15999          0           6         5          0          0           1   

       test_set  
0             0  
1             1  
2             1  
3             0  
4             0  
...         ...  
15995         0  
15996         0  
15997         1  
15998         0  
15999         0  

[16000 rows x 17 columns]

## (2) 데이터 분리

In [243]:
from sklearn.model_selection import train_test_split

# train_set, test_set 분리
train_set = socar_delete[socar_delete["test_set"] == 0]
test_set = socar_delete[socar_delete["test_set"] == 1]

# "test_set" 컬럼 삭제
train_set = train_set.drop("test_set", axis=1)  # test_set = 0인 애들이고, test_set 컬럼을 삭제
test_set = test_set.drop("test_set", axis=1)    # test_set = 1인 애들이고, test_set 컬럼을 삭제

# features와 target분리
X = train_set.drop("fraud_YN", axis=1)         # train_set에서 y라벨 데이터 지움
y = train_set["fraud_YN"]                      # 라벨데이터만 가지고 y변수에 할당

X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.2, random_state=13, stratify=y)
X_test, y_test = test_set.drop("fraud_YN", axis=1), test_set["fraud_YN"]

## (3) SMOTE

In [244]:
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=13)
X_train_over, y_train_over = smote.fit_resample(X, y)

In [245]:
print(np.unique(y, return_counts=True))
print(np.unique(y_train_over, return_counts=True))

(array([0, 1], dtype=int64), array([12845,    34], dtype=int64))
(array([0, 1], dtype=int64), array([12845, 12845], dtype=int64))


## (4) 스케일링

In [246]:
from sklearn.preprocessing import RobustScaler

RS = RobustScaler()

RS.fit(X)

X_rs = RS.transform(X)

In [247]:
X_rs_pd8 = pd.DataFrame(X_rs, columns=X.columns)
X_rs_pd8

car_model  sharing_type  age_group  has_previous_accident  \
0            0.0           1.0        1.0                    0.0   
1            1.0           1.0        1.0                    0.0   
2           -1.0           0.0       -1.0                    0.0   
3           -1.0           1.0        1.0                    0.0   
4            0.0           0.0        2.0                    0.0   
...          ...           ...        ...                    ...   
12874        0.0           0.0        1.0                    1.0   
12875        0.0           0.0        0.0                    0.0   
12876        0.0           0.0        0.0                    1.0   
12877        0.0           0.0        0.0                    0.0   
12878        0.0           0.0        0.0                    0.0   

       cumulative_use_count  b2b  accident_ratio  pf_type  socarpass  \
0                       0.0  0.0             0.0      0.0        0.0   
1                       1.0  0.0          -100.0      0.0        0.0   
2                      -0.5  0.0             0.0     -1.0        0.0   
3                       1.0  0.0             0.0      1.0        0.0   
4                       1.0  0.0          -100.0     -1.0        0.0   
...                     ...  ...             ...      ...        ...   
12874                   1.0  0.0             0.0     -1.0        0.0   
12875                   0.0  0.0             0.0      0.0        0.0   
12876                   1.0  0.0             0.0     -1.0        1.0   
12877                   0.0  0.0             0.0      0.0        0.0   
12878                  -0.5  0.0             0.0     -1.0        0.0   

       socarsave  start_hour  duration  car_part1  car_part2  repair_cnt  
0            0.0    0.000000       0.0        0.0        0.0         0.0  
1            0.0   -0.333333       0.5        1.0        0.0         0.0  
2            0.0   -1.000000      -0.5        0.0        0.0         1.0  
3            0.0    0.666667       0.5        0.0        0.0         0.0  
4            0.0    0.000000       0.0        0.0        0.0         0.0  
...          ...         ...       ...        ...        ...         ...  
12874        0.0    0.000000      -0.5        0.0        0.0         0.0  
12875        0.0   -1.000000      -0.5        1.0        0.0         0.0  
12876        0.0    0.333333       0.0        1.0        0.0         0.0  
12877        0.0    0.666667      -0.5        1.0        0.0         0.0  
12878        0.0    0.666667       1.5        0.0        0.0         0.0  

[12879 rows x 15 columns]

# [원핫인코딩 쓰는 8가지 경우!]

--------------------------------------------------------------------------------

# < 9. 아홉번째 방법 (원핫인코딩 적용, NULL데이터 유지 , SMOTE, 스케일링 없음) >

--------------------------------------------------------------------------------

## 데이터 불러오기

In [248]:
socar_df

fraud_YN  car_model  sharing_type  age_group  has_previous_accident  \
0             0          2             1          3                      0   
1             0          1             0          4                      0   
2             0          1             0          4                      1   
3             0          3             1          3                      0   
4             0          1             0          1                      0   
...         ...        ...           ...        ...                    ...   
15995         0          2             0          2                      0   
15996         0          2             0          2                      1   
15997         0          2             1          2                      0   
15998         0          2             0          2                      0   
15999         0          2             0          2                      0   

       cumulative_use_count  b2b  accident_ratio  pf_type  socarpass  ...  \
0                         2    0             100        2          0  ...   
1                         4    0               0        3          1  ...   
2                         4    0             100        3          1  ...   
3                         4    0               0        2          0  ...   
4                         1    0             100        1          0  ...   
...                     ...  ...             ...      ...        ...  ...   
15995                     2    0             100        2          0  ...   
15996                     4    0             100        1          1  ...   
15997                     4    0             100        1          0  ...   
15998                     2    0             100        2          0  ...   
15999                     1    0             100        1          0  ...   

       insure_cost  accident_location  car_part1  car_part2  repair_cnt  \
0                0                  1          0          0           1   
1                0                  1          1          1           2   
2         12925040                  3          1          0           2   
3                0                  3          1          0           1   
4          1209410                  1          0          0           2   
...            ...                ...        ...        ...         ...   
15995            0                  1          1          0           1   
15996            0                  2          1          0           1   
15997            0                  0          0          0           1   
15998            0                  4          1          0           1   
15999      1188750                  2          0          0           1   

       acc_type1  insurance_site_aid_YN  police_site_aid_YN  total_prsn_cnt  \
0              0                      0                   0              -1   
1              1                      1                   1               0   
2              1                      1                   1               0   
3              0                      0                   0              -1   
4              0                      0                   0              -1   
...          ...                    ...                 ...             ...   
15995          0                      0                   0              -1   
15996          0                      0                   0              -1   
15997          0                      0                   0              -1   
15998          0                      0                   0              -1   
15999          0                      0                   0              -1   

       test_set  
0             0  
1             1  
2             1  
3             0  
4             0  
...         ...  
15995         0  
15996         0  
15997         1  
15998         0  
15999         0  

[16000 rows x 25 columns]

## (1) ONE-HOT_ENCODER

In [249]:
cat_attribs = socar_df.columns.drop(['fraud_YN', 'accident_ratio', 'repair_cost', 'insure_cost', 'repair_cnt', 'test_set'])
                
socar_df = pd.get_dummies(socar_df, columns=cat_attribs)

In [250]:
cat_attribs

Index(['car_model', 'sharing_type', 'age_group', 'has_previous_accident',
       'cumulative_use_count', 'b2b', 'pf_type', 'socarpass', 'socarsave',
       'start_hour', 'duration', 'accident_hour', 'accident_location',
       'car_part1', 'car_part2', 'acc_type1', 'insurance_site_aid_YN',
       'police_site_aid_YN', 'total_prsn_cnt'],
      dtype='object')

In [251]:
socar_df

fraud_YN  accident_ratio   repair_cost  insure_cost  repair_cnt  \
0             0             100  1.302547e+05            0           1   
1             0               0  0.000000e+00            0           2   
2             0             100  2.581306e+05     12925040           2   
3             0               0  1.341009e+06            0           1   
4             0             100  5.240306e+05      1209410           2   
...         ...             ...           ...          ...         ...   
15995         0             100  0.000000e+00            0           1   
15996         0             100  6.184394e+05            0           1   
15997         0             100  0.000000e+00            0           1   
15998         0             100  0.000000e+00            0           1   
15999         0             100  3.915602e+05      1188750           1   

       test_set  car_model_1  car_model_2  car_model_3  car_model_4  ...  \
0             0            0            1            0            0  ...   
1             1            1            0            0            0  ...   
2             1            1            0            0            0  ...   
3             0            0            0            1            0  ...   
4             0            1            0            0            0  ...   
...         ...          ...          ...          ...          ...  ...   
15995         0            0            1            0            0  ...   
15996         0            0            1            0            0  ...   
15997         1            0            1            0            0  ...   
15998         0            0            1            0            0  ...   
15999         0            0            1            0            0  ...   

       insurance_site_aid_YN_2  police_site_aid_YN_0  police_site_aid_YN_1  \
0                            0                     1                     0   
1                            0                     0                     1   
2                            0                     0                     1   
3                            0                     1                     0   
4                            0                     1                     0   
...                        ...                   ...                   ...   
15995                        0                     1                     0   
15996                        0                     1                     0   
15997                        0                     1                     0   
15998                        0                     1                     0   
15999                        0                     1                     0   

       total_prsn_cnt_-1  total_prsn_cnt_0  total_prsn_cnt_1  \
0                      1                 0                 0   
1                      0                 1                 0   
2                      0                 1                 0   
3                      1                 0                 0   
4                      1                 0                 0   
...                  ...               ...               ...   
15995                  1                 0                 0   
15996                  1                 0                 0   
15997                  1                 0                 0   
15998                  1                 0                 0   
15999                  1                 0                 0   

       total_prsn_cnt_2  total_prsn_cnt_3  total_prsn_cnt_4  total_prsn_cnt_5  
0                     0                 0                 0                 0  
1                     0                 0                 0                 0  
2                     0                 0                 0                 0  
3                     0                 0                 0                 0  
4                     0                 0                 0                 0  
...                

## (2) NULL데이터 유지, (3) 데이터 분리

In [252]:
# train_set, test_set 분리
train_set = socar_df[socar_df["test_set"] == 0]
test_set = socar_df[socar_df["test_set"] == 1]

# "test_set" 컬럼 삭제
train_set = train_set.drop("test_set", axis=1)
test_set = test_set.drop("test_set", axis=1)

# features와 target분리
X = train_set.drop("fraud_YN", axis=1)
y = train_set["fraud_YN"]

X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.2, random_state=13, stratify=y)
X_test, y_test = test_set.drop("fraud_YN", axis=1), test_set["fraud_YN"]

## (4) SMOTE

In [253]:
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=13)
X_train_over, y_train_over = smote.fit_resample(X, y)

In [254]:
print(np.unique(y, return_counts=True))
print(np.unique(y_train_over, return_counts=True))

(array([0, 1], dtype=int64), array([12845,    34], dtype=int64))
(array([0, 1], dtype=int64), array([12845, 12845], dtype=int64))


## (5) 스케일링 없음

---------------------------------------------------------------------------------------

# < 10. 열번째 방법 (원핫인코딩 적용, NULL데이터 유지 , SMOTE, 스케일링 MinMax) >

----------------------------------------------------------------------------------------------

## (1)원핫인코딩 적용 (2) NULL데이터 유지, (3) 데이터 분리

In [256]:
# train_set, test_set 분리
train_set = socar_df[socar_df["test_set"] == 0]
test_set = socar_df[socar_df["test_set"] == 1]

# "test_set" 컬럼 삭제
train_set = train_set.drop("test_set", axis=1)
test_set = test_set.drop("test_set", axis=1)

# features와 target분리
X = train_set.drop("fraud_YN", axis=1)
y = train_set["fraud_YN"]

X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.2, random_state=13, stratify=y)
X_test, y_test = test_set.drop("fraud_YN", axis=1), test_set["fraud_YN"]

## (4) SMOTE

In [257]:
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=13)
X_train_over, y_train_over = smote.fit_resample(X, y)

In [259]:
print(np.unique(y, return_counts=True))
print(np.unique(y_train_over, return_counts=True))

(array([0, 1], dtype=int64), array([12845,    34], dtype=int64))
(array([0, 1], dtype=int64), array([12845, 12845], dtype=int64))


## (5) 스케일링

In [264]:
from sklearn.preprocessing import MinMaxScaler

MMS = MinMaxScaler()

MMS.fit(X)

X_mms = MMS.transform(X)

In [265]:
X_mms_pd10 = pd.DataFrame(X_mms, columns=X.columns)
X_mms_pd10

accident_ratio  repair_cost  insure_cost  repair_cnt  car_model_1  \
0                 1.0     0.013409     0.000000    0.027027          0.0   
1                 0.0     0.138052     0.000000    0.027027          0.0   
2                 1.0     0.053947     0.012769    0.054054          1.0   
3                 1.0     0.000000     0.012852    0.027027          1.0   
4                 0.0     0.000000     0.000000    0.027027          0.0   
...               ...          ...          ...         ...          ...   
12874             1.0     0.068696     0.000000    0.027027          0.0   
12875             1.0     0.000000     0.000000    0.027027          0.0   
12876             1.0     0.063666     0.000000    0.027027          0.0   
12877             1.0     0.000000     0.000000    0.027027          0.0   
12878             1.0     0.040310     0.012551    0.027027          0.0   

       car_model_2  car_model_3  car_model_4  car_model_5  sharing_type_0  \
0              1.0          0.0          0.0          0.0             0.0   
1              0.0          1.0          0.0          0.0             0.0   
2              0.0          0.0          0.0          0.0             1.0   
3              0.0          0.0          0.0          0.0             0.0   
4              1.0          0.0          0.0          0.0             1.0   
...            ...          ...          ...          ...             ...   
12874          1.0          0.0          0.0          0.0             1.0   
12875          1.0          0.0          0.0          0.0             1.0   
12876          1.0          0.0          0.0          0.0             1.0   
12877          1.0          0.0          0.0          0.0             1.0   
12878          1.0          0.0          0.0          0.0             1.0   

       ...  insurance_site_aid_YN_2  police_site_aid_YN_0  \
0      ...                      0.0                   1.0   
1      ...                      0.0                   1.0   
2      ...                      0.0                   1.0   
3      ...                      1.0                   0.0   
4      ...                      0.0                   0.0   
...    ...                      ...                   ...   
12874  ...                      0.0                   1.0   
12875  ...                      0.0                   1.0   
12876  ...                      0.0                   1.0   
12877  ...                      0.0                   1.0   
12878  ...                      0.0                   1.0   

       police_site_aid_YN_1  total_prsn_cnt_-1  total_prsn_cnt_0  \
0                       0.0                1.0               0.0   
1                       0.0                1.0               0.0   
2                       0.0                1.0               0.0   
3                       1.0                0.0               0.0   
4                       1.0                0.0               0.0   
...                     ...                ...               ...   
12874                   0.0                1.0               0.0   
12875                   0.0                1.0               0.0   
12876                   0.0                1.0               0.0   
12877                   0.0                1.0               0.0   
12878                   0.0                1.0               0.0   

       total_prsn_cnt_1  total_prsn_cnt_2  total_prsn_cnt_3  total_prsn_cnt_4  \
0                   0.0               0.0               0.0               0.0   
1                   0.0               0.0               0.0               0.0   
2                   0.0               0.0               0.0               0.0   
3                   0.0               1.0               0.0               0.0   
4                   0.0               1.0               0.0               0.0   
...                 ...               ...               ...               ...   
12874               0.0               0.0           

-----------------------------------------------------------------------------------

# < 11. 열한번째 방법 (원핫인코딩 적용, NULL데이터 유지 , SMOTE, 스케일링 Standard) >

---------------------------------------------------------------------------------------


## (1)원핫인코딩 적용 (2) NULL데이터 유지, (3) 데이터 분리

In [130]:
# train_set, test_set 분리
train_set = socar_df[socar_df["test_set"] == 0]
test_set = socar_df[socar_df["test_set"] == 1]

# "test_set" 컬럼 삭제
train_set = train_set.drop("test_set", axis=1)
test_set = test_set.drop("test_set", axis=1)

# features와 target분리
X = train_set.drop("fraud_YN", axis=1)
y = train_set["fraud_YN"]

X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.2, random_state=13, stratify=y)
X_test, y_test = test_set.drop("fraud_YN", axis=1), test_set["fraud_YN"]

## (4) SMOTE

In [266]:
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=13)
X_train_over, y_train_over = smote.fit_resample(X, y)

In [267]:
print(np.unique(y, return_counts=True))
print(np.unique(y_train_over, return_counts=True))

(array([0, 1], dtype=int64), array([12845,    34], dtype=int64))
(array([0, 1], dtype=int64), array([12845, 12845], dtype=int64))


## (5) 스케일링

In [268]:
from sklearn.preprocessing import StandardScaler

SS = StandardScaler()

SS.fit(X)

X_ss = SS.transform(X)

In [269]:
X_ss_pd11 = pd.DataFrame(X_ss, columns=X.columns)
X_ss_pd11

accident_ratio  repair_cost  insure_cost  repair_cnt  car_model_1  \
0            0.367925    -0.296588    -0.273447   -0.382028    -0.847282   
1           -3.009481     2.047627    -0.273447   -0.382028    -0.847282   
2            0.367925     0.465826     0.121310    0.672890     1.180244   
3            0.367925    -0.548781     0.123879   -0.382028     1.180244   
4           -3.009481    -0.548781    -0.273447   -0.382028    -0.847282   
...               ...          ...          ...         ...          ...   
12874        0.367925     0.743205    -0.273447   -0.382028    -0.847282   
12875        0.367925    -0.548781    -0.273447   -0.382028    -0.847282   
12876        0.367925     0.648616    -0.273447   -0.382028    -0.847282   
12877        0.367925    -0.548781    -0.273447   -0.382028    -0.847282   
12878        0.367925     0.209342     0.114566   -0.382028    -0.847282   

       car_model_2  car_model_3  car_model_4  car_model_5  sharing_type_0  \
0         0.969937    -0.198875    -0.089348    -0.146056       -2.375307   
1        -1.030995     5.028287    -0.089348    -0.146056       -2.375307   
2        -1.030995    -0.198875    -0.089348    -0.146056        0.420998   
3        -1.030995    -0.198875    -0.089348    -0.146056       -2.375307   
4         0.969937    -0.198875    -0.089348    -0.146056        0.420998   
...            ...          ...          ...          ...             ...   
12874     0.969937    -0.198875    -0.089348    -0.146056        0.420998   
12875     0.969937    -0.198875    -0.089348    -0.146056        0.420998   
12876     0.969937    -0.198875    -0.089348    -0.146056        0.420998   
12877     0.969937    -0.198875    -0.089348    -0.146056        0.420998   
12878     0.969937    -0.198875    -0.089348    -0.146056        0.420998   

       ...  insurance_site_aid_YN_2  police_site_aid_YN_0  \
0      ...                -0.255806              0.574272   
1      ...                -0.255806              0.574272   
2      ...                -0.255806              0.574272   
3      ...                 3.909210             -1.741335   
4      ...                -0.255806             -1.741335   
...    ...                      ...                   ...   
12874  ...                -0.255806              0.574272   
12875  ...                -0.255806              0.574272   
12876  ...                -0.255806              0.574272   
12877  ...                -0.255806              0.574272   
12878  ...                -0.255806              0.574272   

       police_site_aid_YN_1  total_prsn_cnt_-1  total_prsn_cnt_0  \
0                 -0.574272           0.571403         -0.343748   
1                 -0.574272           0.571403         -0.343748   
2                 -0.574272           0.571403         -0.343748   
3                  1.741335          -1.750079         -0.343748   
4                  1.741335          -1.750079         -0.343748   
...                     ...                ...               ...   
12874             -0.574272           0.571403         -0.343748   
12875             -0.574272           0.571403         -0.343748   
12876             -0.574272           0.571403         -0.343748   
12877             -0.574272           0.571403         -0.343748   
12878             -0.574272           0.571403         -0.343748   

       total_prsn_cnt_1  total_prsn_cnt_2  total_prsn_cnt_3  total_prsn_cnt_4  \
0             -0.317738         -0.173652         -0.111089         -0.075501   
1             -0.317738         -0.173652         -0.111089         -0.075501   
2             -0.317738         -0.173652         -0.111089         -0.075501   
3             -0.317738          5.758629         -0.111089         -0.075501   
4             -0.317738          5.758629         -0.111089         -0.075501   
...                 ...               ...               ...               ...   
12874         -0.317738         -0.173652         -0

-----------------------------------------------------------------------------------

# < 12. 열두번째 방법 (원핫인코딩 적용, NULL데이터 유지 , SMOTE, 스케일링 Robust) >

---------------------------------------------------------------------------------

## (1)원핫인코딩 적용 (2) NULL데이터 유지, (3) 데이터 분리

In [135]:
# train_set, test_set 분리
train_set = socar_df[socar_df["test_set"] == 0]
test_set = socar_df[socar_df["test_set"] == 1]

# "test_set" 컬럼 삭제
train_set = train_set.drop("test_set", axis=1)
test_set = test_set.drop("test_set", axis=1)

# features와 target분리
X = train_set.drop("fraud_YN", axis=1)
y = train_set["fraud_YN"]

X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.2, random_state=13, stratify=y)
X_test, y_test = test_set.drop("fraud_YN", axis=1), test_set["fraud_YN"]

## (4) SMOTE

In [270]:
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=13)
X_train_over, y_train_over = smote.fit_resample(X, y)

In [271]:
print(np.unique(y, return_counts=True))
print(np.unique(y_train_over, return_counts=True))

(array([0, 1], dtype=int64), array([12845,    34], dtype=int64))
(array([0, 1], dtype=int64), array([12845, 12845], dtype=int64))


## (5) 스케일링

In [272]:
from sklearn.preprocessing import RobustScaler

RS = RobustScaler()

RS.fit(X)

X_rs = RS.transform(X)

In [273]:
X_ss_pd12 = pd.DataFrame(X_rs, columns=X.columns)
X_ss_pd12

accident_ratio  repair_cost  insure_cost  repair_cnt  car_model_1  \
0                 0.0    -0.161562     0.000000         0.0          0.0   
1              -100.0     3.181826     0.000000         0.0          0.0   
2                 0.0     0.925814     2.180512         1.0          1.0   
3                 0.0    -0.521249     2.194701         0.0          1.0   
4              -100.0    -0.521249     0.000000         0.0          0.0   
...               ...          ...          ...         ...          ...   
12874             0.0     1.321421     0.000000         0.0          0.0   
12875             0.0    -0.521249     0.000000         0.0          0.0   
12876             0.0     1.186516     0.000000         0.0          0.0   
12877             0.0    -0.521249     0.000000         0.0          0.0   
12878             0.0     0.560009     2.143263         0.0          0.0   

       car_model_2  car_model_3  car_model_4  car_model_5  sharing_type_0  \
0              0.0          0.0          0.0          0.0            -1.0   
1             -1.0          1.0          0.0          0.0            -1.0   
2             -1.0          0.0          0.0          0.0             0.0   
3             -1.0          0.0          0.0          0.0            -1.0   
4              0.0          0.0          0.0          0.0             0.0   
...            ...          ...          ...          ...             ...   
12874          0.0          0.0          0.0          0.0             0.0   
12875          0.0          0.0          0.0          0.0             0.0   
12876          0.0          0.0          0.0          0.0             0.0   
12877          0.0          0.0          0.0          0.0             0.0   
12878          0.0          0.0          0.0          0.0             0.0   

       ...  insurance_site_aid_YN_2  police_site_aid_YN_0  \
0      ...                      0.0                   0.0   
1      ...                      0.0                   0.0   
2      ...                      0.0                   0.0   
3      ...                      1.0                  -1.0   
4      ...                      0.0                  -1.0   
...    ...                      ...                   ...   
12874  ...                      0.0                   0.0   
12875  ...                      0.0                   0.0   
12876  ...                      0.0                   0.0   
12877  ...                      0.0                   0.0   
12878  ...                      0.0                   0.0   

       police_site_aid_YN_1  total_prsn_cnt_-1  total_prsn_cnt_0  \
0                       0.0                0.0               0.0   
1                       0.0                0.0               0.0   
2                       0.0                0.0               0.0   
3                       1.0               -1.0               0.0   
4                       1.0               -1.0               0.0   
...                     ...                ...               ...   
12874                   0.0                0.0               0.0   
12875                   0.0                0.0               0.0   
12876                   0.0                0.0               0.0   
12877                   0.0                0.0               0.0   
12878                   0.0                0.0               0.0   

       total_prsn_cnt_1  total_prsn_cnt_2  total_prsn_cnt_3  total_prsn_cnt_4  \
0                   0.0               0.0               0.0               0.0   
1                   0.0               0.0               0.0               0.0   
2                   0.0               0.0               0.0               0.0   
3                   0.0               1.0               0.0               0.0   
4                   0.0               1.0               0.0               0.0   
...                 ...               ...               ...               ...   
12874               0.0               0.0           

--------------------------------------------------------------------------------

# < 13. 열세번째 방법 (원핫인코딩 적용, NULL데이터 삭제 , SMOTE, 스케일링 없음) >

--------------------------------------------------------------------------------

## (1) NULL 데이터 삭제

In [274]:
socar_delete = socar.drop(['accident_hour', 'repair_cost', 'insure_cost', 'accident_location', 'acc_type1', 'insurance_site_aid_YN', 'police_site_aid_YN', 'total_prsn_cnt'], axis=1)
socar_delete

fraud_YN  car_model  sharing_type  age_group  has_previous_accident  \
0             0          2             1          3                      0   
1             0          1             0          4                      0   
2             0          1             0          4                      1   
3             0          3             1          3                      0   
4             0          1             0          1                      0   
...         ...        ...           ...        ...                    ...   
15995         0          2             0          2                      0   
15996         0          2             0          2                      1   
15997         0          2             1          2                      0   
15998         0          2             0          2                      0   
15999         0          2             0          2                      0   

       cumulative_use_count  b2b  accident_ratio  pf_type  socarpass  \
0                         2    0             100        2          0   
1                         4    0               0        3          1   
2                         4    0             100        3          1   
3                         4    0               0        2          0   
4                         1    0             100        1          0   
...                     ...  ...             ...      ...        ...   
15995                     2    0             100        2          0   
15996                     4    0             100        1          1   
15997                     4    0             100        1          0   
15998                     2    0             100        2          0   
15999                     1    0             100        1          0   

       socarsave  start_hour  duration  car_part1  car_part2  repair_cnt  \
0              0           4         2          0          0           1   
1              0           1         4          1          1           2   
2              0           1         4          1          0           2   
3              0           3         3          1          0           1   
4              0           1         1          0          0           2   
...          ...         ...       ...        ...        ...         ...   
15995          0           1         1          1          0           1   
15996          0           5         2          1          0           1   
15997          0           1         3          0          0           1   
15998          0           6         1          1          0           1   
15999          0           6         5          0          0           1   

       test_set  
0             0  
1             1  
2             1  
3             0  
4             0  
...         ...  
15995         0  
15996         0  
15997         1  
15998         0  
15999         0  

[16000 rows x 17 columns]

## (2) 원핫인코딩 적용

In [275]:
cat_attribs = socar_delete.columns.drop(['fraud_YN', 'accident_ratio', 'repair_cnt', 'test_set'])
                
socar_df = pd.get_dummies(socar_delete, columns=cat_attribs)

In [276]:
socar_df

fraud_YN  accident_ratio  repair_cnt  test_set  car_model_1  \
0             0             100           1         0            0   
1             0               0           2         1            1   
2             0             100           2         1            1   
3             0               0           1         0            0   
4             0             100           2         0            1   
...         ...             ...         ...       ...          ...   
15995         0             100           1         0            0   
15996         0             100           1         0            0   
15997         0             100           1         1            0   
15998         0             100           1         0            0   
15999         0             100           1         0            0   

       car_model_2  car_model_3  car_model_4  car_model_5  sharing_type_0  \
0                1            0            0            0               0   
1                0            0            0            0               1   
2                0            0            0            0               1   
3                0            1            0            0               0   
4                0            0            0            0               1   
...            ...          ...          ...          ...             ...   
15995            1            0            0            0               1   
15996            1            0            0            0               1   
15997            1            0            0            0               0   
15998            1            0            0            0               1   
15999            1            0            0            0               1   

       ...  start_hour_6  duration_1  duration_2  duration_3  duration_4  \
0      ...             0           0           1           0           0   
1      ...             0           0           0           0           1   
2      ...             0           0           0           0           1   
3      ...             0           0           0           1           0   
4      ...             0           1           0           0           0   
...    ...           ...         ...         ...         ...         ...   
15995  ...             0           1           0           0           0   
15996  ...             0           0           1           0           0   
15997  ...             0           0           0           1           0   
15998  ...             1           1           0           0           0   
15999  ...             1           0           0           0           0   

       duration_5  car_part1_0  car_part1_1  car_part2_0  car_part2_1  
0               0            1            0            1            0  
1               0            0            1            0            1  
2               0            0            1            1            0  
3               0            0            1            1            0  
4               0            1            0            1            0  
...           ...          ...          ...          ...          ...  
15995           0            0            1            1            0  
15996           0            0            1            1            0  
15997           0            1            0            1            0  
15998           0            0            1            1            0  
15999           1            1            0            1            0  

[16000 rows x 46 columns]

## (3) 데이터 분리

In [277]:
# train_set, test_set 분리
train_set = socar_df[socar_df["test_set"] == 0]
test_set = socar_df[socar_df["test_set"] == 1]

# "test_set" 컬럼 삭제
train_set = train_set.drop("test_set", axis=1)
test_set = test_set.drop("test_set", axis=1)

# features와 target분리
X = train_set.drop("fraud_YN", axis=1)
y = train_set["fraud_YN"]

X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.2, random_state=13, stratify=y)
X_test, y_test = test_set.drop("fraud_YN", axis=1), test_set["fraud_YN"]

## (4) SMOTE

In [278]:
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=13)
X_train_over, y_train_over = smote.fit_resample(X, y)

In [279]:
print(np.unique(y, return_counts=True))
print(np.unique(y_train_over, return_counts=True))

(array([0, 1], dtype=int64), array([12845,    34], dtype=int64))
(array([0, 1], dtype=int64), array([12845, 12845], dtype=int64))


## (5) 스케일링 없음

-------------------------------------------------------------------

# < 14. 열네번째 방법 (원핫인코딩 적용, NULL데이터 삭제 , SMOTE, 스케일링 (MinMax) >

-------------------------------------------------------------------

## (1) NULL 데이터 삭제, (2) 원핫인코딩 적용,  (3) 데이터 분리

In [153]:
# train_set, test_set 분리
train_set = socar_df[socar_df["test_set"] == 0]
test_set = socar_df[socar_df["test_set"] == 1]

# "test_set" 컬럼 삭제
train_set = train_set.drop("test_set", axis=1)
test_set = test_set.drop("test_set", axis=1)

# features와 target분리
X = train_set.drop("fraud_YN", axis=1)
y = train_set["fraud_YN"]

X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.2, random_state=13, stratify=y)
X_test, y_test = test_set.drop("fraud_YN", axis=1), test_set["fraud_YN"]

## (4) SMOTE

In [280]:
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=13)
X_train_over, y_train_over = smote.fit_resample(X, y)

In [281]:
print(np.unique(y, return_counts=True))
print(np.unique(y_train_over, return_counts=True))

(array([0, 1], dtype=int64), array([12845,    34], dtype=int64))
(array([0, 1], dtype=int64), array([12845, 12845], dtype=int64))


## (5) 스케일링

In [282]:
from sklearn.preprocessing import MinMaxScaler

MMS = MinMaxScaler()

MMS.fit(X)

X_mms = MMS.transform(X)

In [283]:
X_mms_pd14 = pd.DataFrame(X_mms, columns=X.columns)
X_mms_pd14

accident_ratio  repair_cnt  car_model_1  car_model_2  car_model_3  \
0                 1.0    0.027027          0.0          1.0          0.0   
1                 0.0    0.027027          0.0          0.0          1.0   
2                 1.0    0.054054          1.0          0.0          0.0   
3                 1.0    0.027027          1.0          0.0          0.0   
4                 0.0    0.027027          0.0          1.0          0.0   
...               ...         ...          ...          ...          ...   
12874             1.0    0.027027          0.0          1.0          0.0   
12875             1.0    0.027027          0.0          1.0          0.0   
12876             1.0    0.027027          0.0          1.0          0.0   
12877             1.0    0.027027          0.0          1.0          0.0   
12878             1.0    0.027027          0.0          1.0          0.0   

       car_model_4  car_model_5  sharing_type_0  sharing_type_1  age_group_1  \
0              0.0          0.0             0.0             1.0          0.0   
1              0.0          0.0             0.0             1.0          0.0   
2              0.0          0.0             1.0             0.0          1.0   
3              0.0          0.0             0.0             1.0          0.0   
4              0.0          0.0             1.0             0.0          0.0   
...            ...          ...             ...             ...          ...   
12874          0.0          0.0             1.0             0.0          0.0   
12875          0.0          0.0             1.0             0.0          0.0   
12876          0.0          0.0             1.0             0.0          0.0   
12877          0.0          0.0             1.0             0.0          0.0   
12878          0.0          0.0             1.0             0.0          0.0   

       ...  start_hour_6  duration_1  duration_2  duration_3  duration_4  \
0      ...           0.0         0.0         1.0         0.0         0.0   
1      ...           0.0         0.0         0.0         1.0         0.0   
2      ...           0.0         1.0         0.0         0.0         0.0   
3      ...           1.0         0.0         0.0         1.0         0.0   
4      ...           0.0         0.0         1.0         0.0         0.0   
...    ...           ...         ...         ...         ...         ...   
12874  ...           0.0         1.0         0.0         0.0         0.0   
12875  ...           0.0         1.0         0.0         0.0         0.0   
12876  ...           0.0         0.0         1.0         0.0         0.0   
12877  ...           1.0         1.0         0.0         0.0         0.0   
12878  ...           1.0         0.0         0.0         0.0         0.0   

       duration_5  car_part1_0  car_part1_1  car_part2_0  car_part2_1  
0             0.0          1.0          0.0          1.0          0.0  
1             0.0          0.0          1.0          1.0          0.0  
2             0.0          1.0          0.0          1.0          0.0  
3             0.0          1.0          0.0          1.0          0.0  
4             0.0          1.0          0.0          1.0          0.0  
...           ...          ...          ...          ...          ...  
12874         0.0          1.0          0.0          1.0          0.0  
12875         0.0          0.0          1.0          1.0          0.0  
12876         0.0          0.0          1.0          1.0          0.0  
12877         0.0          0.0          1.0          1.0          0.0  
12878         1.0          1.0          0.0          1.0          0.0  

[12879 rows x 44 columns]

--------------------------------------------------------------------------------------

# < 15. 열 다섯번째 방법 (원핫인코딩 적용, NULL데이터 삭제 , SMOTE, 스케일링 (Standard) >

--------------------------------------------------------------------------------------

## (1) NULL 데이터 삭제, (2) 원핫인코딩 적용,  (3) 데이터 분리

In [159]:
# train_set, test_set 분리
train_set = socar_df[socar_df["test_set"] == 0]
test_set = socar_df[socar_df["test_set"] == 1]

# "test_set" 컬럼 삭제
train_set = train_set.drop("test_set", axis=1)
test_set = test_set.drop("test_set", axis=1)

# features와 target분리
X = train_set.drop("fraud_YN", axis=1)
y = train_set["fraud_YN"]

X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.2, random_state=13, stratify=y)
X_test, y_test = test_set.drop("fraud_YN", axis=1), test_set["fraud_YN"]

## (4) SMOTE

In [284]:
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=13)
X_train_over, y_train_over = smote.fit_resample(X, y)

In [285]:
print(np.unique(y, return_counts=True))
print(np.unique(y_train_over, return_counts=True))

(array([0, 1], dtype=int64), array([12845,    34], dtype=int64))
(array([0, 1], dtype=int64), array([12845, 12845], dtype=int64))


## (5) 스케일링

In [286]:
from sklearn.preprocessing import StandardScaler

SS = StandardScaler()

SS.fit(X)

X_ss = SS.transform(X)

In [287]:
X_ss_pd15 = pd.DataFrame(X_ss, columns=X.columns)
X_ss_pd15

accident_ratio  repair_cnt  car_model_1  car_model_2  car_model_3  \
0            0.367925   -0.382028    -0.847282     0.969937    -0.198875   
1           -3.009481   -0.382028    -0.847282    -1.030995     5.028287   
2            0.367925    0.672890     1.180244    -1.030995    -0.198875   
3            0.367925   -0.382028     1.180244    -1.030995    -0.198875   
4           -3.009481   -0.382028    -0.847282     0.969937    -0.198875   
...               ...         ...          ...          ...          ...   
12874        0.367925   -0.382028    -0.847282     0.969937    -0.198875   
12875        0.367925   -0.382028    -0.847282     0.969937    -0.198875   
12876        0.367925   -0.382028    -0.847282     0.969937    -0.198875   
12877        0.367925   -0.382028    -0.847282     0.969937    -0.198875   
12878        0.367925   -0.382028    -0.847282     0.969937    -0.198875   

       car_model_4  car_model_5  sharing_type_0  sharing_type_1  age_group_1  \
0        -0.089348    -0.146056       -2.375307        2.375307    -0.532721   
1        -0.089348    -0.146056       -2.375307        2.375307    -0.532721   
2        -0.089348    -0.146056        0.420998       -0.420998     1.877155   
3        -0.089348    -0.146056       -2.375307        2.375307    -0.532721   
4        -0.089348    -0.146056        0.420998       -0.420998    -0.532721   
...            ...          ...             ...             ...          ...   
12874    -0.089348    -0.146056        0.420998       -0.420998    -0.532721   
12875    -0.089348    -0.146056        0.420998       -0.420998    -0.532721   
12876    -0.089348    -0.146056        0.420998       -0.420998    -0.532721   
12877    -0.089348    -0.146056        0.420998       -0.420998    -0.532721   
12878    -0.089348    -0.146056        0.420998       -0.420998    -0.532721   

       ...  start_hour_6  duration_1  duration_2  duration_3  duration_4  \
0      ...     -0.467878   -0.755768    2.008679   -0.653843   -0.333779   
1      ...     -0.467878   -0.755768   -0.497840    1.529419   -0.333779   
2      ...     -0.467878    1.323158   -0.497840   -0.653843   -0.333779   
3      ...      2.137310   -0.755768   -0.497840    1.529419   -0.333779   
4      ...     -0.467878   -0.755768    2.008679   -0.653843   -0.333779   
...    ...           ...         ...         ...         ...         ...   
12874  ...     -0.467878    1.323158   -0.497840   -0.653843   -0.333779   
12875  ...     -0.467878    1.323158   -0.497840   -0.653843   -0.333779   
12876  ...     -0.467878   -0.755768    2.008679   -0.653843   -0.333779   
12877  ...      2.137310    1.323158   -0.497840   -0.653843   -0.333779   
12878  ...      2.137310   -0.755768   -0.497840   -0.653843   -0.333779   

       duration_5  car_part1_0  car_part1_1  car_part2_0  car_part2_1  
0       -0.199086     0.697001    -0.697001     0.454134    -0.454134  
1       -0.199086    -1.434719     1.434719     0.454134    -0.454134  
2       -0.199086     0.697001    -0.697001     0.454134    -0.454134  
3       -0.199086     0.697001    -0.697001     0.454134    -0.454134  
4       -0.199086     0.697001    -0.697001     0.454134    -0.454134  
...           ...          ...          ...          ...          ...  
12874   -0.199086     0.697001    -0.697001     0.454134    -0.454134  
12875   -0.199086    -1.434719     1.434719     0.454134    -0.454134  
12876   -0.199086    -1.434719     1.434719     0.454134    -0.454134  
12877   -0.199086    -1.434719     1.434719     0.454134    -0.454134  
12878    5.022962     0.697001    -0.697001     0.454134    -0.454134  

[12879 rows x 44 columns]

----------------------------------------------------------------------------

# < 16. 열 여섯번째 방법 (원핫인코딩 적용, NULL데이터 삭제 , SMOTE, 스케일링(Robust) >

------------------------------------------------------------------------

## (1) NULL 데이터 삭제, (2) 원핫인코딩 적용,  (3) 데이터 분리

In [288]:
# train_set, test_set 분리
train_set = socar_df[socar_df["test_set"] == 0]
test_set = socar_df[socar_df["test_set"] == 1]

# "test_set" 컬럼 삭제
train_set = train_set.drop("test_set", axis=1)
test_set = test_set.drop("test_set", axis=1)

# features와 target분리
X = train_set.drop("fraud_YN", axis=1)
y = train_set["fraud_YN"]

X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.2, random_state=13, stratify=y)
X_test, y_test = test_set.drop("fraud_YN", axis=1), test_set["fraud_YN"]

## (4) SMOTE

In [289]:
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=13)
X_train_over, y_train_over = smote.fit_resample(X, y)

In [290]:
print(np.unique(y, return_counts=True))
print(np.unique(y_train_over, return_counts=True))

(array([0, 1], dtype=int64), array([12845,    34], dtype=int64))
(array([0, 1], dtype=int64), array([12845, 12845], dtype=int64))


## (5) 스케일링

In [291]:
from sklearn.preprocessing import RobustScaler

RS = RobustScaler()

RS.fit(X)

X_rs = RS.transform(X)

In [292]:
X_rs_pd16 = pd.DataFrame(X_rs, columns=X.columns)
X_rs_pd16

accident_ratio  repair_cnt  car_model_1  car_model_2  car_model_3  \
0                 0.0         0.0          0.0          0.0          0.0   
1              -100.0         0.0          0.0         -1.0          1.0   
2                 0.0         1.0          1.0         -1.0          0.0   
3                 0.0         0.0          1.0         -1.0          0.0   
4              -100.0         0.0          0.0          0.0          0.0   
...               ...         ...          ...          ...          ...   
12874             0.0         0.0          0.0          0.0          0.0   
12875             0.0         0.0          0.0          0.0          0.0   
12876             0.0         0.0          0.0          0.0          0.0   
12877             0.0         0.0          0.0          0.0          0.0   
12878             0.0         0.0          0.0          0.0          0.0   

       car_model_4  car_model_5  sharing_type_0  sharing_type_1  age_group_1  \
0              0.0          0.0            -1.0             1.0          0.0   
1              0.0          0.0            -1.0             1.0          0.0   
2              0.0          0.0             0.0             0.0          1.0   
3              0.0          0.0            -1.0             1.0          0.0   
4              0.0          0.0             0.0             0.0          0.0   
...            ...          ...             ...             ...          ...   
12874          0.0          0.0             0.0             0.0          0.0   
12875          0.0          0.0             0.0             0.0          0.0   
12876          0.0          0.0             0.0             0.0          0.0   
12877          0.0          0.0             0.0             0.0          0.0   
12878          0.0          0.0             0.0             0.0          0.0   

       ...  start_hour_6  duration_1  duration_2  duration_3  duration_4  \
0      ...           0.0         0.0         1.0         0.0         0.0   
1      ...           0.0         0.0         0.0         1.0         0.0   
2      ...           0.0         1.0         0.0         0.0         0.0   
3      ...           1.0         0.0         0.0         1.0         0.0   
4      ...           0.0         0.0         1.0         0.0         0.0   
...    ...           ...         ...         ...         ...         ...   
12874  ...           0.0         1.0         0.0         0.0         0.0   
12875  ...           0.0         1.0         0.0         0.0         0.0   
12876  ...           0.0         0.0         1.0         0.0         0.0   
12877  ...           1.0         1.0         0.0         0.0         0.0   
12878  ...           1.0         0.0         0.0         0.0         0.0   

       duration_5  car_part1_0  car_part1_1  car_part2_0  car_part2_1  
0             0.0          0.0          0.0          0.0          0.0  
1             0.0         -1.0          1.0          0.0          0.0  
2             0.0          0.0          0.0          0.0          0.0  
3             0.0          0.0          0.0          0.0          0.0  
4             0.0          0.0          0.0          0.0          0.0  
...           ...          ...          ...          ...          ...  
12874         0.0          0.0          0.0          0.0          0.0  
12875         0.0         -1.0          1.0          0.0          0.0  
12876         0.0         -1.0          1.0          0.0          0.0  
12877         0.0         -1.0          1.0          0.0          0.0  
12878         1.0          0.0          0.0          0.0          0.0  

[12879 rows x 44 columns]